hydra:
  searchpath:
    - file://conf

defaults:
  - modchembert-config
  - _self_

pretrained_model_path: training_output/release/ModChemBERT-MLM-DAPT-TAFT-OPT
metric: rms_score # mean_squared_error | mean_absolute_error | rms_score | mae_score
transform: true # Whether to apply norm/log transform to the target values for regression tasks.
# The following can also be defined per-dataset in dataset_hyperparameters if needed.
use_normalized_weight_decay: false # https://arxiv.org/pdf/1711.05101.pdf
weight_decay: 0.0 # Only used if use_normalized_weight_decay is false.
optimizer: adam # adam | stable_adamw
torch_dtype: bfloat16 # float32 | float16 | bfloat16

datasets:
  - bace_regression
  - clearance
  - delaney # ESOL
  - freesolv
  - lipo
  - adme_microsom_stab_h
  - adme_microsom_stab_r
  - adme_permeability
  - adme_ppb_h
  - adme_ppb_r
  - adme_solubility
  - astrazeneca_cl
  - astrazeneca_logd74
  - astrazeneca_ppb
  - astrazeneca_solubility

dataset_hyperparameters:
  bace_regression:
    batch_size: 32
    epochs: 100
    learning_rate: 3e-5
    classifier_pooling: max_seq_mha
    classifier_pooling_last_k: 5
    classifier_pooling_attention_dropout: 0.1
    classifier_dropout: 0.0
    embedding_dropout: 0.0
  clearance:
    batch_size: 32
    epochs: 100
    learning_rate: 3e-5
    classifier_pooling: max_seq_mha
    classifier_pooling_last_k: 5
    classifier_pooling_attention_dropout: 0.1
    classifier_dropout: 0.0
    embedding_dropout: 0.0
  delaney:
    batch_size: 64
    epochs: 100
    learning_rate: 3e-5
    classifier_pooling: sum_mean
    classifier_pooling_last_k: 3
    classifier_pooling_attention_dropout: 0.1
    classifier_dropout: 0.0
    embedding_dropout: 0.1
  freesolv:
    batch_size: 32
    epochs: 100
    learning_rate: 3e-5
    classifier_pooling: max_seq_mha
    classifier_pooling_last_k: 5
    classifier_pooling_attention_dropout: 0.1
    classifier_dropout: 0.0
    embedding_dropout: 0.0
  lipo:
    batch_size: 32
    epochs: 100
    learning_rate: 3e-5
    classifier_pooling: max_seq_mha
    classifier_pooling_last_k: 3
    classifier_pooling_attention_dropout: 0.1
    classifier_dropout: 0.1
    embedding_dropout: 0.1
    use_normalized_weight_decay: true
  adme_microsom_stab_h:
    batch_size: 16
    epochs: 100
    learning_rate: 3e-5
    classifier_pooling: max_seq_mha
    classifier_pooling_last_k: 3
    classifier_pooling_attention_dropout: 0.1
    classifier_dropout: 0.0
    embedding_dropout: 0.1
  adme_microsom_stab_r:
    batch_size: 16
    epochs: 100
    learning_rate: 3e-5
    classifier_pooling: max_seq_mha
    classifier_pooling_last_k: 5
    classifier_pooling_attention_dropout: 0.1
    classifier_dropout: 0.0
    embedding_dropout: 0.1
  adme_permeability:
    batch_size: 8
    epochs: 100
    learning_rate: 3e-05
    classifier_pooling: max_cls
    classifier_pooling_last_k: 3
    classifier_pooling_attention_dropout: 0.1
    classifier_dropout: 0.0
    embedding_dropout: 0.1
  adme_ppb_h:
    batch_size: 32
    epochs: 100
    learning_rate: 1e-05
    classifier_pooling: max_seq_mean
    classifier_pooling_last_k: 5
    classifier_pooling_attention_dropout: 0.1
    classifier_dropout: 0.0
    embedding_dropout: 0.1
  adme_ppb_r:
    batch_size: 32
    epochs: 100
    learning_rate: 1e-5
    classifier_pooling: max_seq_mha
    classifier_pooling_last_k: 5
    classifier_pooling_attention_dropout: 0.1
    classifier_dropout: 0.0
    embedding_dropout: 0.1
  adme_solubility:
    batch_size: 32
    epochs: 100
    learning_rate: 3e-5
    classifier_pooling: max_seq_mha
    classifier_pooling_last_k: 5
    classifier_pooling_attention_dropout: 0.1
    classifier_dropout: 0.0
    embedding_dropout: 0.1
  astrazeneca_cl:
    batch_size: 32
    epochs: 100
    learning_rate: 3e-5
    classifier_pooling: max_seq_mha
    classifier_pooling_last_k: 3
    classifier_pooling_attention_dropout: 0.1
    classifier_dropout: 0.0
    embedding_dropout: 0.0
  astrazeneca_logd74:
    batch_size: 16
    epochs: 100
    learning_rate: 3e-5
    classifier_pooling: max_seq_mean
    classifier_pooling_last_k: 5
    classifier_pooling_attention_dropout: 0.1
    classifier_dropout: 0.1
    embedding_dropout: 0.1
  astrazeneca_ppb:
    batch_size: 32
    epochs: 100
    learning_rate: 1e-5
    classifier_pooling: max_cls
    classifier_pooling_last_k: 3
    classifier_pooling_attention_dropout: 0.1
    classifier_dropout: 0.0
    embedding_dropout: 0.1
  astrazeneca_solubility:
    batch_size: 32
    epochs: 100
    learning_rate: 1e-5
    classifier_pooling: max_seq_mean
    classifier_pooling_last_k: 5
    classifier_pooling_attention_dropout: 0.1
    classifier_dropout: 0.0
    embedding_dropout: 0.1
